AllCops:
  Exclude:
    - user_interface.rb
    - main.rb

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 110

Metrics/MethodLength:
  Enabled: true
  Max: 20

Style/Documentation:
  Enabled: false

